FROM 123.59.151.144:5000/centos

MAINTAINER wangfei "wangfei@chunyu.me"

RUN mkdir -p /usr/local/ip/
RUN mkdir -p /usr/local/ip/log

ADD ip_query/qqwry.dat /usr/local/ip/qqwry.dat
ADD iplocation /usr/local/ip/

ADD control.sh /usr/local/ip/
ADD config.test.ini /usr/local/ip/config.ini

# 脚本不能在后台运行
CMD /usr/local/ip/iplocation -c /usr/local/ip/config.ini -L /usr/local/ip/log/ip.log &> /usr/local/ip/log/app.log

