// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package ip_service

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type IpService interface {
	// 根据IP获取相关的Location
	//
	// Parameters:
	//  - Ip
	IpToLocation(ip string) (r *Location, err error)
}

type IpServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewIpServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *IpServiceClient {
	return &IpServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewIpServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *IpServiceClient {
	return &IpServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// 根据IP获取相关的Location
//
// Parameters:
//  - Ip
func (p *IpServiceClient) IpToLocation(ip string) (r *Location, err error) {
	if err = p.sendIpToLocation(ip); err != nil {
		return
	}
	return p.recvIpToLocation()
}

func (p *IpServiceClient) sendIpToLocation(ip string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("IpToLocation", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := IpServiceIpToLocationArgs{
		Ip: ip,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *IpServiceClient) recvIpToLocation() (value *Location, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "IpToLocation" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "IpToLocation failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "IpToLocation failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "IpToLocation failed: invalid message type")
		return
	}
	result := IpServiceIpToLocationResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Re != nil {
		err = result.Re
		return
	}
	value = result.GetSuccess()
	return
}

type IpServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      IpService
}

func (p *IpServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *IpServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *IpServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewIpServiceProcessor(handler IpService) *IpServiceProcessor {

	self2 := &IpServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["IpToLocation"] = &ipServiceProcessorIpToLocation{handler: handler}
	return self2
}

func (p *IpServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type ipServiceProcessorIpToLocation struct {
	handler IpService
}

func (p *ipServiceProcessorIpToLocation) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := IpServiceIpToLocationArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("IpToLocation", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := IpServiceIpToLocationResult{}
	var retval *Location
	var err2 error
	if retval, err2 = p.handler.IpToLocation(args.Ip); err2 != nil {
		switch v := err2.(type) {
		case *RpcException:
			result.Re = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing IpToLocation: "+err2.Error())
			oprot.WriteMessageBegin("IpToLocation", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("IpToLocation", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Ip
type IpServiceIpToLocationArgs struct {
	Ip string `thrift:"ip,1" json:"ip"`
}

func NewIpServiceIpToLocationArgs() *IpServiceIpToLocationArgs {
	return &IpServiceIpToLocationArgs{}
}

func (p *IpServiceIpToLocationArgs) GetIp() string {
	return p.Ip
}
func (p *IpServiceIpToLocationArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *IpServiceIpToLocationArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Ip = v
	}
	return nil
}

func (p *IpServiceIpToLocationArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("IpToLocation_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *IpServiceIpToLocationArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("ip", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ip: ", p), err)
	}
	if err := oprot.WriteString(string(p.Ip)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.ip (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ip: ", p), err)
	}
	return err
}

func (p *IpServiceIpToLocationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IpServiceIpToLocationArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - Re
type IpServiceIpToLocationResult struct {
	Success *Location     `thrift:"success,0" json:"success,omitempty"`
	Re      *RpcException `thrift:"re,1" json:"re,omitempty"`
}

func NewIpServiceIpToLocationResult() *IpServiceIpToLocationResult {
	return &IpServiceIpToLocationResult{}
}

var IpServiceIpToLocationResult_Success_DEFAULT *Location

func (p *IpServiceIpToLocationResult) GetSuccess() *Location {
	if !p.IsSetSuccess() {
		return IpServiceIpToLocationResult_Success_DEFAULT
	}
	return p.Success
}

var IpServiceIpToLocationResult_Re_DEFAULT *RpcException

func (p *IpServiceIpToLocationResult) GetRe() *RpcException {
	if !p.IsSetRe() {
		return IpServiceIpToLocationResult_Re_DEFAULT
	}
	return p.Re
}
func (p *IpServiceIpToLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IpServiceIpToLocationResult) IsSetRe() bool {
	return p.Re != nil
}

func (p *IpServiceIpToLocationResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *IpServiceIpToLocationResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &Location{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *IpServiceIpToLocationResult) ReadField1(iprot thrift.TProtocol) error {
	p.Re = &RpcException{}
	if err := p.Re.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Re), err)
	}
	return nil
}

func (p *IpServiceIpToLocationResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("IpToLocation_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *IpServiceIpToLocationResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *IpServiceIpToLocationResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetRe() {
		if err := oprot.WriteFieldBegin("re", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:re: ", p), err)
		}
		if err := p.Re.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Re), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:re: ", p), err)
		}
	}
	return err
}

func (p *IpServiceIpToLocationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IpServiceIpToLocationResult(%+v)", *p)
}
